# Generated by Django 3.1 on 2020-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomm', '0002_auto_20200905_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateprofile',
            name='school',
            field=models.CharField(choices=[('E', 'Cockrell School of Engineering'), ('L', 'School of Liberal Arts'), ('M', 'Mccombs School of Business'), ('N', 'School of Natural Sciences'), ('S', 'School of Social Work')], max_length=1),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='workout',
            field=models.CharField(choices=[('Y', 'Yes, I workout.'), ('N', "No, I don't workout"), ('O', 'Occasionally, I workout.')], max_length=1),
        ),
    ]
