# Generated by Django 3.1 on 2020-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublease',
            name='aptname',
            field=models.TextField(),
        ),
    ]
