# Generated by Django 3.1 on 2020-09-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subl', '0002_auto_20200902_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublease',
            name='contact',
            field=models.CharField(default='example@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sublease',
            name='opento',
            field=models.CharField(choices=[('M', 'Males'), ('F', 'Females'), ('E', 'Any')], max_length=1),
        ),
    ]
