# Generated by Django 3.1 on 2020-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('west', '0005_apartment_area'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='west.Apartment'),
        ),
    ]
