# Generated by Django 3.1 on 2020-08-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('west', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
